server:
  port: 8080

spring:
  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/master.xml
    enabled: true

  config:
    import: optional:file:.env[.properties]

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  show-actuator: false
  swagger-ui:
    try-it-out-enabled: true
    filter: true
    path: /swagger-ui.html

encryption:
  secret: ${ENCRYPT_SECRET_KEY}